# Generated by Django 3.2.5 on 2023-01-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=500)),
                ('password2', models.CharField(max_length=30)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(choices=[('IND', 'India'), ('PAK', 'Pakistan'), ('BAN', 'Bangladesh'), ('CH', 'China'), ('US', 'Usa')], default='IND', max_length=3)),
                ('otp_counter', models.IntegerField(default=0)),
                ('is_admin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('password2', models.CharField(max_length=30)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('posistion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('response', models.CharField(choices=[('PEN', 'Pending'), ('ACT', 'Accept'), ('RJT', 'Reject')], default='PEN', max_length=3)),
                ('vacationFile', models.FileField(blank=True, null=True, upload_to='files')),
                ('employee', models.ManyToManyField(to='crm_app.Employee')),
            ],
        ),
    ]
