# Generated by Django 3.2.5 on 2023-01-19 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_auto_20230119_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
